//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Murder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stat()
        {
            this.Characters = new HashSet<Character>();
            this.Items = new HashSet<Item>();
        }
    
        public long StatsId { get; set; }
        public Nullable<int> Strength { get; set; }
        public Nullable<int> Dexterity { get; set; }
        public Nullable<int> Agility { get; set; }
        public Nullable<int> Wisdom { get; set; }
        public Nullable<int> Intelligence { get; set; }
        public Nullable<int> Charisma { get; set; }
        public Nullable<int> Constitution { get; set; }
        public Nullable<int> ElectricResist { get; set; }
        public Nullable<int> WaterResist { get; set; }
        public Nullable<int> FireResist { get; set; }
        public Nullable<int> EarthResist { get; set; }
        public Nullable<int> HolyResist { get; set; }
        public Nullable<int> DarkResist { get; set; }
        public Nullable<int> ElectricBonus { get; set; }
        public Nullable<int> WaterBonus { get; set; }
        public Nullable<int> FireBonus { get; set; }
        public Nullable<int> EarthBonus { get; set; }
        public Nullable<int> HolyBonus { get; set; }
        public Nullable<int> DarkBonus { get; set; }
        public Nullable<int> Armor { get; set; }
        public Nullable<int> MagicResist { get; set; }
        public Nullable<int> ArmorPenetration { get; set; }
        public Nullable<int> MagicPenetration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Character> Characters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
