//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Murder
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCurrency
    {
        public long UserId { get; set; }
        public int CurrencyId { get; set; }
        public int Amount { get; set; }
        public long UserCurrencyId { get; set; }
    
        public virtual User User { get; set; }
        public virtual CurrencyType CurrencyType { get; set; }
    }
}
